//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyConv.MoneyConvSrv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MoneyConvSrv.IMoneyConvV1")]
    public interface IMoneyConvV1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoneyConvV1/ConvertNumberToWords", ReplyAction="http://tempuri.org/IMoneyConvV1/ConvertNumberToWordsResponse")]
        MoneyConv.Common.Interfaces.ApiResponse<string> ConvertNumberToWords(string currencyValue);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMoneyConvV1Channel : MoneyConv.MoneyConvSrv.IMoneyConvV1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MoneyConvV1Client : System.ServiceModel.ClientBase<MoneyConv.MoneyConvSrv.IMoneyConvV1>, MoneyConv.MoneyConvSrv.IMoneyConvV1 {
        
        public MoneyConvV1Client() {
        }
        
        public MoneyConvV1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MoneyConvV1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoneyConvV1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoneyConvV1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MoneyConv.Common.Interfaces.ApiResponse<string> ConvertNumberToWords(string currencyValue) {
            return base.Channel.ConvertNumberToWords(currencyValue);
        }
    }
}
